# Generated by Django 5.0.4 on 2024-05-06 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='ciudad',
            table='Ciudad',
        ),
        migrations.AlterModelTable(
            name='estadoentrega',
            table='EstadoEntrega',
        ),
        migrations.AlterModelTable(
            name='estadoorden',
            table='EstadoOrden',
        ),
        migrations.AlterModelTable(
            name='pais',
            table='Pais',
        ),
        migrations.AlterModelTable(
            name='tipodocumento',
            table='TipoDocumento',
        ),
    ]
