# Generated by Django 5.0.4 on 2024-05-06 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reparto', '0002_ubicacion_alter_entrega_ubicacion'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='entrega',
            table='Entrega',
        ),
        migrations.AlterModelTable(
            name='ubicacion',
            table='Ubicacion',
        ),
    ]
