# Generated by Django 5.0.4 on 2024-04-24 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('descripcion', models.CharField(max_length=500, verbose_name='Descripción')),
                ('imagen', models.ImageField(upload_to='imagen/', verbose_name='Imagen')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('descripcionBreve', models.CharField(max_length=100, verbose_name='Descripción breve')),
                ('descripcionExtendida', models.CharField(max_length=500, verbose_name='Descripción extendida')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio')),
                ('imagenPrincipal', models.ImageField(upload_to='imagen/', verbose_name='Imagen principal')),
                ('imagenSecundaria1', models.ImageField(upload_to='imagen/', verbose_name='Imagen secundaria 1')),
                ('imagenSecundaria2', models.ImageField(upload_to='imagen/', verbose_name='Imagen secundaria 2')),
                ('imagenSecundaria3', models.ImageField(upload_to='imagen/', verbose_name='Imagen secundaria 3')),
                ('imagen3D', models.ImageField(upload_to='imagen/', verbose_name='Imagen 3D')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
    ]
