# Generated by Django 5.0.4 on 2024-05-06 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_remove_orden_ubicacion_orden_entrega_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cliente',
            table='Cliente',
        ),
        migrations.AlterModelTable(
            name='detalleorden',
            table='DetalleOrden',
        ),
        migrations.AlterModelTable(
            name='orden',
            table='Orden',
        ),
        migrations.AlterModelTable(
            name='pago',
            table='Pago',
        ),
    ]
