# Generated by Django 5.0.4 on 2024-04-25 01:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='categoria',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='web.categoria', verbose_name='Categoría'),
            preserve_default=False,
        ),
    ]
