# Generated by Django 5.0.4 on 2024-04-30 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='numero_documento',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Número de documento'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='tipo_documento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.tipodocumento', verbose_name='Tipo de documento'),
        ),
    ]
