# Generated by Django 5.0.4 on 2024-05-06 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_remove_producto_categoria_remove_ciudad_pais_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='empleado',
            table='Empleado',
        ),
    ]
