# Generated by Django 5.0.4 on 2024-05-01 23:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_alter_ubicacion_latitud_alter_ubicacion_longitud'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrega',
            name='detalles_entrega',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Anotaciones del encargado de la entrega'),
        ),
        migrations.AlterField(
            model_name='entrega',
            name='empleado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.empleado', verbose_name='Empleado asignado'),
        ),
    ]
