# Generated by Django 5.0.4 on 2024-04-29 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_alter_usuario_managers_usuario_date_joined_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='tipoDocumento',
        ),
    ]
